// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZYo9z-pQHqZqHamnv4ixaCslkBkUnDE0',
    appId: '1:362558307860:android:908575f6dadf008f1e7101',
    messagingSenderId: '362558307860',
    projectId: 'tasks-d1abf',
    databaseURL: 'https://tasks-d1abf-default-rtdb.firebaseio.com',
    storageBucket: 'tasks-d1abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-R5IVXQcOYi6I3Ga5-HlHHqtajXXYS4',
    appId: '1:362558307860:ios:48ec0eec04fe147f1e7101',
    messagingSenderId: '362558307860',
    projectId: 'tasks-d1abf',
    databaseURL: 'https://tasks-d1abf-default-rtdb.firebaseio.com',
    storageBucket: 'tasks-d1abf.firebasestorage.app',
    iosBundleId: 'com.tariqul.checkInMaster',
  );
}
